config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :tasks
  end
  devise_for :users
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  #resources :tasks
  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
    belongs_to :user
    has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy, :show]

  # GET /lists or /lists.json
  def index
    @lists = List.where(user_id: current_user.id)
  end

  # GET /lists/1 or /lists/1.json
  def show
    @list = List.find(params[:id])

    @tasks = @list.tasks
  end

  # GET /lists/new
  def new
    #@list = List.new
    @list = current_user.lists.build
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    #@list = List.new(list_params)
    @list = current_user.lists.build(list_params)
    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: "List was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy!

    respond_to do |format|
      format.html { redirect_to lists_path, notice: "List was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  def correct_user
    @list = current_user.lists.find_by(id: params[:id])
    redirect_to lists_path, alert: "Boa tentativa" if @list.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.expect(list: [ :title, :user_id ])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :set_list, only: %i[ show new create destroy edit update ]
  before_action :correct_user, only: [:edit, :update, :destroy, :show]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    #@task = Task.new
    @task = @list.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = @list.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @list, notice: "Task was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @list, notice: "Task was successfully updated.", status: :see_other }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to @list, notice: "Task was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  def correct_user
    @list = current_user.lists.find_by(id: params[:list_id])
    redirect_to lists_path, alert: "Boa tentativa" if @list.nil?
  end

  private
    def set_list
      @list = List.find(params[:list_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.expect(task: [ :description, :completed, :list_id ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/_nav.html.erb
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <%= link_to "Todo Lists", root_path, class: "navbar-brand"%>
                
                <div class="collapse navbar-collapse" id="navbarNav">

                    <ul class="navbar-nav ms-auto">

                        <% if user_signed_in? %>
                            <li class="nav-item">
                                <%= link_to "Lists", lists_path, class: "nav-link" %>
                            </li>
                            <li class="nav-item">
                                <%= link_to "New List", new_list_path, class: "nav-link" %>
                            </li>
                            <li class="nav-item">
                                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
                            </li>
                            <li class="nav-item">
                                <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
                            </li>
                        <%else%>
                            <li class="nav-item">
                                <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
                            </li>
                            <li class="nav-item">
                                <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
                            </li>
                        <% end %>

                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

app/views/home/index.html.erb
<h2>Welcome to Todo - Lists</h2>
<%if user_signed_in?%>
<%= link_to "Your Lists", lists_path, class: "btn btn-primary"%>
<%= link_to "Create a new list", new_list_path, class: "btn btn-primary"%>
<%else%>
<h3>Sign-in or Sign-up to proceed</h3>
<%end%>

app/views/layouts/_alerts.html.erb
<% if alert %>
    <div class="alert alert-danger" role="alert">
        <%= alert %>
    </div>
<% elsif notice %>
    <div class="alert alert-warning" role="alert">
        <%= notice %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= content_for(:title) || "Todo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>
  <body>
    <header>
      <%= render 'home/nav'%>
    </header>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    <div class="container" >
      <br>
      <%= render 'layouts/alerts' %>
      <br>
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, style: "display: block", class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div>
    <%= form.number_field :user_id, id: :list_user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>">
  <p>
    <li><h3><%= list.title %></h3></li>
  </p>

</div>

app/views/lists/edit.html.erb
<% content_for :title, "Editing list" %>

<h1>Editing list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Show this list", @list %> |
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/index.html.erb
<% content_for :title, "Lists" %>

<h1>Lists:</h1>

<div id="lists">
  <% @lists.each do |list| %>
    <ul>
      <%= render list %>
    </ul>
    <p>
      <%= link_to "Show this list", list, class: "btn btn-dark"%>
    </p>
  <% end %>
</div>

<%= link_to "New list", new_list_path, class: "btn btn-primary" %>

app/views/lists/new.html.erb
<% content_for :title, "New list" %>

<h1>New list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to lists", lists_path, class: "btn btn-warning" %>
</div>

app/views/lists/show.html.erb
<h1>Tasks from list: <%= @list.title%></h1>

<% if @tasks.any? %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Description</th>
        <th scope="col">Completed?</th>
        <th scope="col">Edit</th>
        <th scope="col">Remove</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.description %>
          <td><%= check_box_tag "completed", task.id, task.completed, class: 'form-check-input', disabled: true %>
          <td><%= link_to "Edit", edit_list_task_path(@list, task), class: "btn btn-primary" %>
          <td><%= button_to "Destroy", list_task_path(@list, task), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>This list has no tasks.</p>
<% end %>

<div>
  <%= link_to "Add Task to List", new_list_task_path(@list), class: "btn btn-success" %> 
  <%= link_to "Rename", edit_list_path(@list), class: "btn btn-primary" %> 
  <%= link_to "Back to lists", lists_path, class: "btn btn-warning" %>
  <%= button_to "Destroy this list", @list, method: :delete, class: "btn btn-danger" %>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: [@list,@task]) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block", class: "form-label" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div>
    <%= form.label :completed, style: "display: block", class: "form-label" %>
    <%= form.checkbox :completed, class: "form-check-input" %>
  </div>

  <div>
    <%= form.number_field :list_id, type: :hidden %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= task.completed %>
  </p>

</div>

app/views/tasks/edit.html.erb
<% content_for :title, "Editing task" %>

<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", list_path(@list), class: "btn btn-warning" %>
</div>

app/views/tasks/index.html.erb
<% content_for :title, "Tasks" %>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", list_path(@list) %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<% content_for :title, "New task" %>

<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", list_path(@list), class: "btn btn-warning" %>
</div>

app/views/tasks/show.html.erb
<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_list_task_path(@task) %> |
  <%= link_to "Back to list", list_path(@list) %>

  <%= button_to "Destroy this task", list_task_path, method: :delete, data: { confirm: "Are you sure?" } %>
</div>